apiVersion: v1
kind: Pod
metadata:
  name: urotaxipod
  labels:
    version: "1.0"    
spec:
  containers:
  - name: urotaxicon
    image: mgmbcssantosh86/urotaxi:1.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - name: tomcatport
        containerPort: 8089
        protocol: TCP
    readinessProbe:
      httpGet:
        path: /actuator/health/readiness
        port: 8080
      initialDelaySeconds: 5
      timeoutSeconds: 10
      failureThreshold: 3
    livenessProbe:
      httpGet:
        path: /actuator/health/liveness
        port: 8080
      initialDelaySeconds: 5
      timeoutSeconds: 10
      failureThreshold: 3