apiVersion: v1
kind: Pod
metadata:
  name: roadsterpod
spec:
  containers:
    - name: roadstercontainer
      image: mgmbcssantosh86/roadster:1.0
      ports:
        - name: tomcatports
          containerPort: 8080
          protocol: TCP
      readinessProbe:
        httpGet:
          path: /roadster/actuator/health/readiness
          port: 8080
        initialDelaySeconds: 10
        timeoutSeconds: 10
        failureThreshold: 3
      livenessProbe:
        httpGet:
          path: /roadster/actuator/health/liveness
          port: 8080
        initialDelaySeconds: 10
        timeoutSeconds: 10
        failureThreshold: 3
      resources:
        requests:
          cpu: "500m"
          memory: "512Mi"
        limits:
          cpu: "1"
          memory: "1024Mi"